name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Build and test
        run: |
          export GOPATH=/home/runner/go
          export GOBIN=$GOPATH/bin
          export PATH=$PATH:$GOBIN
          mkdir -p $GOBIN

          export PROJDIR=$GOPATH/src/github.com/oasislabs
          export SRCDIR=$PROJDIR/ledger-go
          mkdir -p "${PROJDIR}"
          ln -s "$(pwd)" "${SRCDIR}"
          cd "${SRCDIR}"
          go get -v -u github.com/golang/dep/cmd/dep
          dep ensure -v
          go build ledger.go apduWrapper.go
          go test
